FROM alpine:latest AS final


WORKDIR /app

COPY --from=lunanightbyte/gorecord-base:v0.0.1 /compiled/server ./server


# Expose the port the server listens on
EXPOSE 8055

# Start the application
CMD ["./server"]

