FROM alpine:latest AS final


WORKDIR /app

COPY --from=lunanightbyte/gorecord-base:latest /compiled/server ./server
RUN mkdir -p /app/internal/settings
COPY ./internal/settings/* /app/internal/settings
COPY ./internal/settings/db /app/internal/settings/db
# Expose the port the server listens on
EXPOSE 80

# Start the application
CMD ["./server"]

