name: Go Record Webui

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-push:
    environment: "Docker Build Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB secrets are missing!"
            exit 1
          else
            echo "DOCKERHUB secrets found."
          fi
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Base
        run: |
          docker build -f docker/Dockerfile.base -t lunanightbyte/gorecord-base:${{ env.VERSION }} .
          docker tag lunanightbyte/gorecord-base:${{ env.VERSION }} lunanightbyte/gorecord-base:latest
      - name: Push Base image
        run: |
          docker push lunanightbyte/gorecord-base:${{ env.VERSION }}
          docker push lunanightbyte/gorecord-base:latest

      - name: Build Minimal
        run: |
          docker build -f docker/Dockerfile.run -t lunanightbyte/gorecord:${{ env.VERSION }} .
          docker tag lunanightbyte/gorecord:${{ env.VERSION }} lunanightbyte/gorecord:latest
          
      - name: Push Minimal image
        run: |
          docker push lunanightbyte/gorecord:${{ env.VERSION }}
          docker push lunanightbyte/gorecord:latest
